      <div class="row">
        <div class="col-sm-12 sourcing-banner"> 
        <img src='<?php echo $this->getViewFileUrl('Knowpapa_Sourcing::images/sourcing.png'); ?>' alt="image-icon" width="403" height="484" class="responsive">
        
        </div>
        <div class="col-sm-12">
          <form class="form contact" action="<?php echo $block->getFormAction() ?>" id="sourcing-form" method="post" data-hasrequired="* Required Fields"  novalidate="novalidate" enctype="multipart/form-data">
            <fieldset class="fieldset">
              <legend class="legend"><span>Complete Your RFQ - Tell suppliers what you need</span></legend>
              <br>
              <div class="field note no-label">The more specific your information, the more accurately we can match your request to the right suppliers.</div>
              <div class="field keywords required">
                <div class="control">
                  <input placeholder="keywords of products you are looking for" name="keywords" id="keywords" title="keywords" value="" class="input-text" data-validate="{required:true}" aria-required="true" type="text">
                </div>
              </div>
              <div class="field quantity required">
                <div class="control">
                  <input placeholder="Quantity required (e.g 1000 pcs)" name="quantity" id="quantity" title="quantity" value="" class="input-text" type="text" data-validate="{required:true}">
                </div>
              </div>
              <div class="field location required">
                <div class="control">
                  <input placeholder="Location of delivery (City, State)" name="location" id="location" title="location" value="" class="input-text" type="text" data-validate="{required:true}">
                </div>
              </div>
              <div class="field specification required">
                <div class="control">
                  <textarea placeholder="Hi,&#10;I'm looking for products with the following specifications:" name="specification" id="specification" title="What’s on your mind?" class="input-text" cols="5" rows="3" data-validate="{required:true}" aria-required="true"></textarea>
                </div>
              </div>
              <input type="hidden" value="" name="attachmentCount" />
              <div class="field uploads">
                <div id="filesContainer" class="control">
                  <p id="inValidExtensionError" style="display:none; color:#FF0000;">Invalid file extension. Allowed extensions: .jpg, .jpeg, .png, .pdf </p>
                  <div id="element-templates">
                    <div class="templaterow">::FIELD2::: <input type="file" name="::FIELD3::"  data-validate="{validate-fileextensions:true}"></div>
                  </div>
                  <p><a id="add-file-upload" class="add-file-upload">add new attachment</a> <span class="small">allowed files: .jpg,.png, .pdf, .docx, .xlsx </span></p>
                  
                </div>
              </div>
            </fieldset>
            <div class="actions-toolbar">
              <div class="primary">
                <input value="submit" id="sourcingsubmit" type="submit" title="Submit" class="action submit primary" >
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
<style>
  .small{
    font-size: 80%;
    color: #6e6e6e;
    }
  .templaterow {
    display: none;
    }
    .newlyAdded{
      margin:5px;
      }
    .sourcing-banner{
      padding: 30px;
      margin: 15px auto;
      }  
      .add-file-upload:before {
      display: inline-block;
      font-family: FontAwesome;
      font-style: normal;
      font-weight: 400;
      line-height: 1;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      content: "\f055";
      font-size: 16px;
      padding: 0 5px;
      color: #c2185b;
}
      
  </style>
<script>
require([
    'jquery',
    'mage/validation'
    
], function($){

    var dataForm = $('#sourcing-form');
    var ignore = null;

    dataForm.mage('validation', {
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    }).find('input:text').attr('autocomplete', 'off');

    $('button#sourcingsubmit').click( function() { //can be replaced with any event
        dataForm.validation('isValid'); //validates form and returns boolean
    });
});
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Knowpapa_Sourcing/js/sourcing": {}
        }
    }

</script>
